---
abstract: unknown
author:
  - 'Kuerbis <cuer2s@gmail.com>'
build_requires:
  Test::More: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.84, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-YTDL
no_index:
  directory:
    - t
    - inc
requires:
  Encode: 0
  Encode::Locale: 0
  Exporter: 0
  Fcntl: 0
  File::Basename: 0
  File::HomeDir: 0
  File::Spec::Functions: 0
  FindBin: 0
  Getopt::Long: 0
  JSON::XS: 0
  LWP::UserAgent: 0
  List::MoreUtils: 0
  List::Util: 0
  Pod::Usage: 0
  Term::ANSIScreen: 0
  Term::Choose: 0
  Term::Size::Any: 0
  Text::LineFold: 0
  Time::HiRes: 0
  Try::Tiny: 0
  URI: 0
  URI::Escape: 0
  Unicode::GCString: 0
  Unicode::Normalize: 0
  WWW::YouTube::Download: 0
  XML::LibXML: 0
  perl: 5.010001
resources:
  repository: https://github.com/kuerbis/App-YTDL.git
version: 0.008
